In [1]:
!pip install numpy
!pip install pandas

In [2]:
import numpy as np
b = np.empty([3,3])
print(b)

[[6.85230802e-310 5.47982877e-310 6.85228257e-310]
 [6.85228257e-310 6.85228257e-310 6.85228257e-310]
 [6.85228257e-310 6.85228257e-310 3.95252517e-322]]


In [3]:
b = np.zeros([2,2])
print(b)

[[0. 0.]
 [0. 0.]]


In [4]:
import numpy as np

a = np.array([5, 10, 11, 13])
print(a)

b = np.array([6, 8, 10, 11])  # Changed to have 4 elements
print(b)



add = np.add(a,b)
sub = np.subtract(a,b)
mult = np.multiply(a,b)
divi = np.divide(a,b)

[ 5 10 11 13]
[ 6  8 10 11]


In [5]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
b = np.arange(10,1,-2)
print(b)
b1 = b[3]
print(b1)

[10  8  6  4  2]
4


In [7]:
a = np.arange(10, 1, -2)
a1 = a[np.array([3, 1, 2])]
print(a1)

[4 8 6]


In [8]:
a = np.array(20)
print(a)

20


### Pandas

In [9]:
import pandas as pd

In [10]:
ser = pd.Series()
print(ser)

Series([], dtype: object)


In [11]:
a = np.array([1,2,3,4,5])
ser = pd.Series(a)
print(ser)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [12]:
data = {
    "Name": ['a','b','c'],
    'Roll' : [11,12,13],
    'Ph.no': [111, 112,123]
}

df = pd.DataFrame(data)
print(df)

  Name  Roll  Ph.no
0    a    11    111
1    b    12    112
2    c    13    123


In [13]:
gr = df.groupby('Name')
print(gr)

In [ ]:
a = int()